baseurl = "https://mcfelix.me/"
languageCode = "en-GB"
title = "Kyle Simpson"
theme = "felix"

# Code Highlighting stuff
pygmentsCodeFences = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Kyle A. Simpson"
  description = "Portfolio and personal blog site of Kyle A. Simpson."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []
  hideReadingTime = false

[params.social]
  github        = "FelixMcFelix"
  email         = "kyleandrew.simpson@gmail.com"
  twitter       = "McFelixFelix"
  mastodon      = "https://hachyderm.io/@FelixMcFelix"
  bsky          = "felixmcfelix.bsky.social"
  linkedIn      = "kyle-simpson-b0944bb0"
  stackoverflow = ""
  bandcamp      = ""
  keybase       = ""

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "blog/"
[[menu.main]]
  name = "publications"
  identifier = "publication"
  weight = 200
  url = "publication/"
[[menu.main]]
  name = "projects"
  identifier = "project"
  weight = 500
  url = "project/"
[[menu.main]]
  name = "résumé"
  identifier = "resume"
  weight = 300
  url = "kyle-simpson-us-resume.pdf"
  pre = "yup"
[[menu.main]]
  name = "cv"
  identifier = "cv"
  weight = 400
  url = "kyle-simpson.pdf"
  pre = "yup"

[markup]
  [markup.highlight]
    tabWidth = 4