baseurl = "https://mcfelix.me/"
languageCode = "en-GB"
title = "Kyle Simpson"
theme = "felix"
themep = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Kyle A. Simpson"
  description = "Portfolio and personal blog site of Kyle A. Simpson."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  github        = "FelixMcFelix"
  email         = "kyleandrew.simpson@gmail.com"
  twitter       = "Mach60KAS"
  linkedIn      = "kyle-simpson-b0944bb0"
  stackoverflow = ""
  bandcamp      = ""

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "blog/"
[[menu.main]]
  name = "projects"
  identifier = "project"
  weight = 200
  url = "project/"
[[menu.main]]
  name = "resumé"
  identifier = "resume"
  weight = 300
  url = "Vitae-KSimpson.pdf"
